  
# datasource
spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/lagou_work?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: "root"
    password: "123456"
